cargo-features = ["edition2024"]

[package]
name = "flying-sim-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0-alpha.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
bitvec = "1"
